GET http://localhost:3000/products

###
GET http://localhost:3000/products/1111
###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "tv 32",
    "description": "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. In elementis mé pra quem é amistosis quis leo. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. Cevadis im ampola pa arma uma pindureta.",
    "image_url": "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218fHx8fHx8fHwxNjIzMzQ0NjY2&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit",
    "price": 1500.99
}

###
PATCH http://localhost:3000/products/4bd3c819-0c32-4723-a8c9-c247c7cf603d
Content-Type: application/json

{
    "name": "tv 32 alterada",
    "price": 1500.80
}

###
DELETE http://localhost:3000/products/21203833-a260-4db0-9b4d-9cffa6917d47

## ORDERS ####

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/f6e32915-ccfb-40e3-8935-ec6c5f9720d3


###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "credit_card": {
      "number": "1111111111111103",
      "name": "Filipe Cardoso",
      "expiration_month": 10,
      "expiration_year": 2023,
      "cvv": "123"
    },
       "items":  [
      {
          "quantity": 1, 
          "product_id": "3ac5d988-3cbd-45fc-b661-4b26901d8f07"
      }
   ]
}

# {
#    "credit_card": {
#       "number": "1111111111111103",
#       "name": "Luiz carlos",
#       "expiration_month": 6,
#       "expiration_year": 2021,
#       "cvv": "123"
#    },
#    "items":  [
#       {
#           "quantity": 2, 
#           "product_id": "8ea4791a-9534-4f45-b172-f22a7e2b90c3"
#       }
#    ]
# }